FROM debian:sid

RUN apt-get update && apt-get install -y \
        curl \
        python3 \
        python3-dev \
        python3-pip \
        clang-15 \
        llvm-15 \
        lld-15

COPY requirements.txt /opt/compylo/
RUN pip install -r /opt/compylo/requirements.txt pre-commit

WORKDIR /opt/compylo

RUN curl -LO \
https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-17/wasi-sysroot-17.0.tar.gz \
&& tar xzvf wasi-sysroot-17.0.tar.gz

RUN  curl -LO \
https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-17/libclang_rt.builtins-wasm32-wasi-17.0.tar.gz \
&& tar xzvf libclang_rt.builtins-wasm32-wasi-17.0.tar.gz

RUN ln -s $(which clang-15) /usr/bin/clang
RUN ln -s $(which python3) /usr/bin/python
RUN rm -rf *.tar.gz
RUN echo 'alias clang-wasm="clang --target=wasm32-unknown-wasi --sysroot=/opt/compylo/wasi-sysroot -lc /opt/compylo/lib/wasi/libclang_rt.builtins-wasm32.a"' >> .bashrc \
&& echo 'alias ls="ls --color=auto"' >> .bashrc
